idcos/cloudiac

runner/command.go
=> feat: runner 启动 worker 容器前先尝试进行 image pull

portal/apps/template_export.go, portal/libs/db/mysql_gorm.go, portal/models/models.go, portal/services/template_import.go
=> feat: 云模板导入时会检查 id 是否与己删除的数据重复

portal/services/vcsrv/gitea.go
=> refa: gitea仓库列表取用户下的仓库列表

policy/policy.go, portal/apps/policy_group.go, portal/consts/consts.go, portal/consts/e/errors.go, portal/models/forms/policy.go, portal/models/policy.go, portal/models/policy_group.go, portal/services/policy_group.go, utils/utils.go
=> Feat: 策略组创建流程

docs/mkdocs/deploy/container.md, docs/mkdocs/deploy/host.md, portal/apps/auth.go, portal/models/forms/sso.go, portal/models/token.go, portal/services/sso_token.go, portal/services/token.go, portal/web/api/v1/handlers/sso.go
1. /sso/tokens
2. /sso/tokens/verify
3. 文档的版本是make时自动更新的
=> SSO token 相关接口

portal/apps/system_config.go, portal/models/forms/policy_group.go, portal/web/api/v1/handlers/policy_group.go, portal/web/api/v1/route.go, utils/reverse_proxy.go
- 调用registry侧API完成策略组列表查询
- 调用registry侧API完成策略组版本列表查询
=> 策略组列表和版本的API

cmds/portal/main.go, portal/apps/system_config.go, portal/consts/consts.go, portal/models/sys_cfg.go, portal/services/system_config.go, portal/services/vcsrv/registry.go, portal/services/vcsrv/registry_test.go, portal/services/vcsrv/vcservice.go
基于 registry侧的接口，实现 registry vcs
=> 实现 registry vcs

configs/config.go, portal/apps/variables_group.go, portal/services/export_import.go, portal/services/export_import_test.go, utils/variables.go
如果导出时敏感变量没有 secret: 前缀会导致没有先解密就被导出
=> fix: 修复导出云模板时敏感变量处理问题

portal/apps/webhook.go
=> Fix: 修复触发器触发归档环境部署问题 

portal/models/json_ext.go, runner/api/v1/handler/task_log_test.go, utils/http_client.go
=> Fix err check lint

portal/services/vcsrv/local.go, portal/services/vcsrv/vcservice.go, scripts/updatedocs/main.go, utils/http_client.go
=> Fix cognitive complexity

portal/apps/user.go
=> Fix cognitive complexity user相关

portal/apps/resource_account.go, portal/apps/task.go, portal/apps/template.go
=> Fix cognitive complexity portal apps 相关代码

portal/web/middleware/rbac.go, utils/http_client.go
=> Fix ineffectual assignment

portal/apps/policy.go, portal/services/policy_rel.go
修复不启用扫描情况下获取策略扫描结果报错
修复修改环境策略绑定错误
=> Fix: update env policy

portal/task_manager/manager.go, portal/task_manager/task_done_actions.go, runner/api/v1/handler/task.go, runner/task.go, runner/types.go
在2个位置对clone下的仓库代码进行清理
1. task执行出错的时候
2. task完成，stop的时候
=> Fix workspace disk 占用过高问题

portal/apps/task.go
=> fix: SearchTask() 重复 join user表的问题

portal/apps/env.go
环境归档后名称添加后缀"archived{timestamp}"
=> feat: 环境归档后名称添加后缀

portal/services/policy_rel.go
GetPolicyRels() 查询时没有过滤 scope，导致查询模板的关联策略组时把环境上绑定的也返回了。
其他函数也是类似问题。
=> fix: 修复策略组关联关系 db 操作未正确处理 scope 的问题

portal/models/forms/notification.go, portal/models/forms/policy.go, portal/models/forms/project_user.go, portal/models/forms/resource_account.go, portal/models/forms/task_comment.go, portal/models/forms/template.go, portal/models/forms/token.go, portal/models/forms/variable_group.go, portal/models/forms/webhook.go, portal/web/api/v1/handlers/env.go, portal/web/api/v1/handlers/notification.go, portal/web/api/v1/handlers/organization.go, portal/web/api/v1/handlers/policy.go, portal/web/api/v1/handlers/policy_env.go, portal/web/api/v1/handlers/policy_group.go, portal/web/api/v1/handlers/policy_suppress.go, portal/web/api/v1/handlers/policy_template.go, portal/web/api/v1/handlers/project.go, portal/web/api/v1/handlers/project_user.go, portal/web/api/v1/handlers/resource_account.go, portal/web/api/v1/handlers/system_config.go, portal/web/api/v1/handlers/system_status.go, portal/web/api/v1/handlers/task.go, portal/web/api/v1/handlers/task_comment.go, portal/web/api/v1/handlers/template.go, portal/web/api/v1/handlers/token.go, portal/web/api/v1/handlers/user.go, portal/web/api/v1/handlers/variable_group.go, portal/web/api/v1/handlers/vcs.go, portal/web/api/v1/handlers/webhook.go
=> Fix:修复swagger文档

portal/models/resource.go, portal/services/resource.go, portal/services/task.go
=> Feat resource filed

portal/apps/env.go
=> Fix task step timeout

portal/models/resource.go, portal/services/resource.go, portal/services/task.go
=> fix:优化resource资源添加字段

portal/models/forms/env.go, portal/services/env.go
创建环境sampleVar新增sensitive敏感变量字段
=> feat:创建环境sampleVar新增敏感变量字段

portal/apps/env.go, portal/apps/template.go, portal/web/api/v1/handlers/env.go, portal/web/api/v1/route.go
=> Feat env deploy check

go.mod, portal/apps/variables_group.go, portal/models/resps/variables.go, portal/services/variables_group.go
=> FIX : update resource account project_id

cmds/tool/bill.go, portal/apps/env.go, portal/apps/project.go, portal/services/bill.go, portal/task_manager/cron.go
只要环境所在项目有绑定开启了计费的资源账号则环境就开启了计费，不需要考虑资源账号是否应用到了环境。
因为有可能获取账单使用的单独的账号，并不会用于创建环境，也不会应用到环境。
=> change: 修改环境是否启用计费的判断逻辑

portal/apps/env.go, portal/models/env.go, portal/services/env.go, portal/services/project.go, portal/task_manager/task_done_actions.go
修改的地方各个commit中有说明。
帮忙看看是否有遗漏或者误修改的地方。
=> 环境增加"已销毁"状态

portal/models/task.go, portal/task_manager/task_step.go, runner/task.go
- terraformApply 步骤增加采集资源信息需要的命令，在 terraform apply 命令后执行
- 单独的资源采集步骤只在任务未执行 terraformApply 即结束的情况下调用
=> apply 结束后即执行资源采集

portal/apps/project.go, portal/models/forms/project.go, portal/models/resps/project.go, portal/services/project.go
项目列表接口增加资源趋势数据。
接口参数中增加 withStat 参数，withStat == true 时，返回资源趋势数据。
不传入withStat参数或者 withStat == false，不返回资源趋势数据。
=> 项目列表接口增加资源趋势统计数据

cmds/common/register.go, cmds/portal/main.go, cmds/runner/main.go, utils/consul/consul_client.go
=> consul重启自动重连

portal/models/env.go
=> auto migrate env status field

runner/task.go
关联 #210 
修改方案参见 [checkout 步骤出错会导致任务无法采集环境资源信息](https://idcos.yuque.com/kyco54/rgsunw/zcx294)
=> fix checkout 步骤出错会导致任务无法采集环境资源信息

portal/apps/template_export.go
=> fix 导入云模板时的无效参数提示

portal/services/organization.go
组织概览中项目统计的过滤条件中增加 status = enable。包括：
1. 环境状态占比
2. 资源类型占比
3. 项目资源数量
4. 资源新增趋势
=> 组织概览中项目统计的过滤条件

configs/config-portal.yml.sample, configs/dotenv.sample, go.mod, portal/services/vcs.go
- 解决字符串双引号 
- 解决无default 值变量无法引入
=> FIX : 修复变量引入相关问题 

portal/services/env.go
fix CLOUDIAC-205
修改主要内容：
1. 环境费用类型统计中，对res_id 去重后统计
2. 环境费用趋势统计中，对res_id 去重后统计
=> Fix 环境费用统计bug

portal/consts/e/errors.go, portal/services/env.go
=> 环境趋势数据补充缺失的月份数据

portal/apps/auth.go
=> 修复登陆401没有提示

portal/apps/env.go, portal/services/env.go
增加 
```
JOIN iac_env ON
iac_env.id = iac_resource.env_id
and iac_resource.task_id = iac_env.last_res_task_id
```
=> 资源列表检索方法调整

portal/apps/ldap.go, portal/models/forms/ldap.go, portal/services/ldap.go, portal/web/api/v1/route.go
简化3授权接口的参数：
1. /ldap/auth/project_ou
2. /ldap/auth/org_user
3. /ldap/auth/org_ou
=> 调整ldap授权接口参数

portal/services/project.go
=> Fix bug - cloudiac 233

portal/apps/auth.go, portal/services/user.go
=> fix ladp 用户登录错误

portal/services/forecast/providers/terraform/alicloud/alicloud_db_instance.go, portal/services/forecast/providers/terraform/alicloud/alicloud_disk.go, portal/services/forecast/providers/terraform/alicloud/alicloud_eip.go, portal/services/forecast/providers/terraform/alicloud/alicloud_eip_address.go, portal/services/forecast/providers/terraform/alicloud/alicloud_mongodb_instance.go, portal/services/forecast/providers/terraform/alicloud/alicloud_nat_gateway.go, portal/services/forecast/providers/terraform/alicloud/alicloud_slb.go, portal/services/forecast/providers/terraform/alicloud/alicloud_slb_load_balancer.go, portal/services/forecast/providers/terraform/alicloud/alicoud_ecs_disk.go, portal/services/forecast/providers/terraform/alicloud/registry.go, portal/services/forecast/reource/alicloud/alicloud_db_instance.go, portal/services/forecast/reource/alicloud/alicloud_disk.go, portal/services/forecast/reource/alicloud/alicloud_ecs_disk.go, portal/services/forecast/reource/alicloud/alicloud_eip.go, portal/services/forecast/reource/alicloud/alicloud_eip_address.go, portal/services/forecast/reource/alicloud/alicloud_mongodb_instance.go, portal/services/forecast/reource/alicloud/alicloud_nat_gateway.go, portal/services/forecast/reource/alicloud/alicloud_slb.go, portal/services/forecast/reource/alicloud/alicloud_slb_load_balancer.go
- 完成ecs/redis/yundisk/slb/rds/mongodb/eip/nat网关对接
=> refa: 基于新的询价服务重新对接阿里云产品

portal/apps/ldap.go, portal/models/forms/ldap.go, portal/models/resps/ldap.go, portal/services/ldap.go
1. ldap OU 列表（from db） 增加过滤项目的参数
2. ldap user 授权 多人同时授权
3. ldap user 列表（from ldap） 增加检索条件（mail模糊检索）和返回结果的数量限制
=> 更新ldap api 接口参数

portal/services/organization.go, portal/services/project.go
=> Fix cloudiac 245

portal/apps/ldap.go, portal/models/resps/ldap.go, portal/services/ldap.go
=> Feat ldap displayname

cmds/portal/main.go, docs/lang.csv, portal/apps/auth.go, portal/apps/user.go, portal/consts/consts.go, portal/consts/e/errors.go, portal/consts/e/lang.go, portal/libs/ctx/service_ctx.go, portal/models/forms/token.go, portal/models/resps/system.go, portal/models/resps/token.go, portal/models/user.go, portal/services/token.go, portal/web/api/v1/handlers/auth.go, portal/web/api/v1/handlers/user.go, portal/web/api/v1/route.go, portal/web/middleware/auth.go
=> Refa activate

docs/lang.csv, portal/apps/env.go, portal/consts/e/errors.go, portal/consts/e/lang.go
=> demo环境的锁定后端控制

configs/config-portal.yml.sample, configs/config.go, docs/lang.csv, portal/apps/template.go, portal/consts/e/errors.go, portal/consts/e/lang.go, portal/services/demo_org.go
=> 演示云模板不可编辑,删除

go.mod, portal/models/resource.go, portal/models/resps/organization.go, portal/services/organization.go, portal/services/task.go
- resourec 表增加 dependencies 字段存储 tfstate 的 dependencies 数据;
- resource 查询接口支持展示 dependencies 数据;
=> feat: 资源查询接口支持展示依赖数据

cmds/tool/db.go, cmds/tool/main.go, portal/services/sync_provider_res.go, portal/services/task.go
tool support complete all resource dependencies;
=> Feat: tool support dependencies

configs/rbac.go, docs/mkdocs/product-deploy/container.md, docs/mkdocs/product-deploy/host.md, docs/mkdocs/releases.md
* update: version
* fix: 项目审批员权限问题
=> Dev0.12.1 

portal/models/resps/platform.go, portal/services/platform.go, portal/web/api/v1/handlers/platform.go
返回值格式调整为：https://idcos.yuque.com/wbw5km/vdot62/dm1slb#wvtmY
=> 修改活跃资源数量接口的返回值格式

portal/services/platform.go
=> fix orgid 字段误写成id

portal/apps/env.go, portal/consts/consts.go, portal/models/env.go, portal/models/forms/env.go, portal/services/task_auto_deploy.go, portal/task_manager/manager.go, portal/task_manager/task_done_actions.go
文档：https://idcos.yuque.com/kyco54/rgsunw/blhqst
=> 环境自动部署和自动销毁功能

portal/apps/platform_today.go, portal/models/resps/platform.go, portal/services/platform_today.go, portal/web/api/v1/handlers/platform_today.go, portal/web/api/v1/route.go
参考文档：https://idcos.yuque.com/wbw5km/vdot62/iyn68t
=> 平台管理员当日统计数据

runner/task.go
=> fix: 修复 _cloudiac.tfvars.json 文件生成问题

configs/config.go, go.mod, portal/apps/provider_cache.go, portal/consts/urls.go, portal/models/forms/provider_cache.go, portal/web/api/v1/handlers/provider_cache.go, portal/web/api/v1/route.go, runner/api/v1/handler/provider_cache.go, runner/api/v1/route.go, runner/helper.go, runner/types.go
=> feat: 清理provider缓存

portal/services/task.go
=> fix(terraform plan result 问题修复): env

.gitignore, portal/apps/env.go
Fix 周期切换具体时间时，周期表达式未清空/周期自动销毁后，重新部署存活时间变为不限制
=> Fix 周期切换具体时间时，周期表达式未清空/周期自动销毁后，重新部署存活时间变为不限制

portal/apps/variables_group.go
=> Fix 资源账号分页显示单页

portal/services/task.go
=> 优化 Kafka 成功发送消息后的日志输出

configs/config-portal.yml.sample, configs/config.go, configs/dotenv.sample, docs/mkdocs/product-deploy/container.md, portal/web/main.go
新增SwaggerEnable变量，通过配置文件控制Swagger文档开放
=>  feat:添加SwaggerEnable变量控制Swagger文档开放 

portal/web/middleware/auth.go
=> feat: 优化 checkOrgId 时数据库错误的报错

configs/config-portal.yml.sample, configs/dotenv.sample, docs/mkdocs/product-deploy/container.md
=> style:修正SWAGGER_ENABLE变量格式

portal/apps/vcs.go, portal/services/vcsrv/gitea.go, portal/services/vcsrv/gitee.go, portal/services/vcsrv/github.go, portal/services/vcsrv/gitlab.go, portal/services/vcsrv/local.go, portal/services/vcsrv/registry.go, portal/services/vcsrv/vcservice.go
fix:修复无法识别对ansible进行软链接后的路径 （gitlab、gitea、github、gitee)
=> fix:修复无法识别软链接ansible的文件路径

portal/apps/env.go, portal/consts/consts.go, portal/models/resps/env.go, portal/services/env.go
This PR has the following changes:
=> feat: env resource list optimization

portal/services/env.go
This PR has the following changes:
remove order by for MonthEnvCost sql.
=> update: remove order by for MonthEnvCost sql

portal/apps/env.go, portal/consts/consts.go, portal/models/resps/env.go
This PR has the following changes:
active resource fee support region.
=> feat: env resource list support region

portal/apps/env.go, portal/apps/task.go, portal/apps/token.go, portal/libs/ctx/service_ctx.go, portal/models/env.go, portal/models/forms/token.go, portal/models/resps/task.go, portal/models/resps/token.go, portal/models/task.go, portal/models/token.go, portal/services/env.go, portal/services/task.go, portal/services/token.go, portal/web/middleware/auth.go
This PR has the following changes:
- API Token support name(create/update/search).
- API Token hide token key.
- Env api resp support token name.
- Task table and env table add token id field.
- token table data migration.
=> feat: api token support name, other api support token name

portal/apps/env.go, portal/models/resps/env.go
This pr has changes that env resource list support availability zone.
=> feat: env resource list support availability zone

portal/services/tag.go
* fix: env depoly tags error
* del: 删除多余入参
=> fix: env depoly tags error (#798)
