idcos/cloudiac

cmds/tool/demo.go
portal/apps/env.go
portal/apps/variables.go
portal/consts/e/e.go
portal/consts/e/errors.go
portal/models/forms/env.go
portal/models/forms/template.go
portal/models/forms/variable.go
portal/models/models.go
portal/models/variables.go
portal/services/env.go
portal/services/user.go
portal/services/variables.go
portal/web/api/v1/handlers/variable.go
portal/web/api/v1/route.go

- 新增接口: /variables/scope/{scope}/{objectId}，用于更新实例的变量列表
- 修改环境创建接口：variables 参数只支持传入环境级别的变量
- 修改环境部署接口：移除 delVariables 参数，variables 参数设计为全量更新, variables 中不存在的变量会被删除
resolve #68

Feat: 变量更新接口改为只支持传当前实例添加的变量

---

portal/models/models.go

升级到 mysql 8.0 后默认会使用 utf8mb4_0900_ci，但 5.7 版本默认为 utf8_general_ci，
当字段值有特殊符号时(如 emoji 符号) 将无法进行两种类型的转换，所以需要统一 collection。
又因为我们需要同时兼容 mysql 5.7 和 8.0，utf8mb4_0900_ci 在 5.7 中还未引入，所以选择 utf8mb4_unicode_ci。

change: 修改 mysql table 的 collate 为 utf8mb4

---

runner/task.go

terrascan 1.9 会把 Dockerfile 解析出来，并且格式和 terraform 的有点不一样，导致 json unmarshal 出错，添加限制为只解析 terraform 文件。

fix: 云模板解析只解析 terraform 文件

---

portal/libs/db/mysql_gorm.go
portal/models/policy.go
portal/services/project.go
portal/services/template.go
portal/services/user.go
portal/services/vcsrv/vcservice.go

使用 Table() 时不会自动处理软删除，所以需要进行修复。
目前使用软删除特性的 model 有: env、policy、project、runner_task、template、user。
其中 policy 在 0.9 版本中会从 vcs 中导入，所有不再需要软删除。
其他 model 使用了 Table() 调用的地方都改为了 Model() 或者其查询语句中己经加上了 deleted_at_t = 0 条件

fix: 修复部分查询未正常处理软删除的问题

---

portal/services/user.go

使用 db.First(&dest) 查询数据时总是使用 First() 传入的 struct 做字段映射,
前面通过的 Model() 指定的 struct 不生效。

fix: 查询用户详情报 user.role 字段不存在

---

cmds/portal/main.go
configs/config-portal.yml.sample
configs/config.go
portal/apps/system_config.go
portal/apps/vcs.go
portal/consts/consts.go
portal/consts/e/errors.go
portal/models/forms/system_config.go
portal/models/sys_cfg.go
portal/services/system_config.go
portal/services/vcs.go
portal/web/api/v1/handlers/system_config.go
portal/web/api/v1/route.go

包含内容如下：
1. 配置文件中增加 registryAddr 的配置
2. 判断registry addr是否存在的API
3. 获取registry addr的API
4. 更新或插入registry addr的API
5. 系统启动时初始化 registry vcs的信息到数据库
6. 检索vcs时默认不检索 registry vcs 的信息

feat: registry home url 配置及初始化

---

portal/apps/policy.go
portal/libs/page/page.go

1. 该接口不需要返回 models.EnvDetail 结构里的字段，且使用 EnvDetail 做 Scan() 时会因为其中有 PolicyGroup 字段，同时 PolicyGroups 字段的 NewPolicyGroup 结构里又组合了 models.PolicyGroup，最终导致 gorm 认为我们是在做关联查询，自动查询了 model PolicyGroup，但因为 PolicyGroup 的字段类型为 []string 而非 struct，会报一个数据类型不匹配的错误。
2. envIds 未写入数据，导致没有查询到 policyGroups

fix: 合规中心->环境，列表展示的绑定策略组无返回的问题

---

portal/models/forms/system_config.go

去除设置 registryaddr的接口中， registryaddr不能为空的限制

fix 允许页面清空 registryaddr的值

---

portal/services/task.go
portal/task_manager/manager.go
portal/task_manager/task.go
runner/api/v1/handler/task_log.go
runner/api/v1/handler/task_status.go
runner/command.go
runner/committed_task.go
runner/docker_client.go
runner/task.go

因为暂停容器的逻辑有多处，且暂停容器的调用是定时检查，
暂停操作调用不及时，可能出现后续步骤己启动执行，
但前续步骤的容器暂停逻辑才被调用，导致容器被异常暂停。
解决方案：
1. 我们对容器暂停功能不是强需求，现在只在 task.Wait() 函数中执行容器暂停，该调用会在任务结束后及时触发。
2. 在等待容器中进程结束时判断容器是否被暂停，如果被暂停则报错，及时反馈，避免一直不退出。
同时该 commit 还对 docker client 的创建进行了优化，重用了全局的 defautlDockerClient，避免重复创建连接占用 fd。

fix: 任务 plan 失败后仍显示为执行中

---

cmds/portal/main.go
cmds/runner/main.go
common/consts.go
portal/apps/env.go
portal/apps/system_status.go
portal/models/env.go
portal/models/forms/env.go
portal/services/env.go
portal/services/system_status.go
portal/web/api/v1/handlers/system_status.go
portal/web/api/v1/route.go
utils/utils.go

按照tags匹配runner，并且兼容之前按照id匹配runner的方式。
修改涉及的API主要内容包括：
1.  变更（PUT /api/v1/consul/tags/update）增加权限控制，只有平台管理员可以编辑runner的tag
2.  新增（GET /api/v1/runners/tags），返回所有的tags
3.  变更（POST /api/v1/envs），runner相关参数增加runner_tags数组，为了兼容之前的环境runner_id参数保留。
4.  变更（GET /api/v1/envs/{envId}），返回值中增加runner_tags信息。
5.  变更（GET /api/v1/envs），返回值中增加runner_tags信息。
6.  变更（POST /api/v1/envs/:id/deploy）deploy时，根据选择的runner_tags，确定一个runner_id

基于 tag 的 runner 匹配

---

portal/apps/task.go
portal/models/forms/task.go
portal/web/api/v1/handlers/env.go

●查询环境部署历史的接口增加筛选字段: 任务类型、触发类型、执行人姓名、执行人邮箱
● 其中姓名和邮箱为模糊搜索，其他字段为全词匹配

部署历史增加筛选条件

---

portal/apps/task.go

-  规则示例1: 如果资源的属性中有 `public_i`p 字段，则展示 `public_ip`
-  规则示例2: 如果资源的属性中有 `name` 字段，则展示 `name`
-  规则示例3: 如果资源的属性中有 `tag` 字段，则展示 `name(tag1,tag2)`
- `resource address(id)`, 如：`module1.alicloud_instance.web(i-xxxxxxx)`

Feat optimize resource display name

---

cmds/portal/main.go
common/consts.go
portal/apps/env.go
portal/apps/token.go
portal/apps/webhook.go
portal/models/env.go
portal/models/forms/env.go
portal/models/runner_task.go
portal/models/sys_cfg.go
portal/services/system_config.go

1. iac_system_cfg 表增加 name 为TASK_STEP_TIMEOUT 的记录, 默认值为 3600 (60分钟)
2. 平台设置页面增加步骤超时时间设置, 用于修改 TASK_STEP_TIMEOUT
3. 环境创建, 更新, 重新部署时可以配置步骤超时时间，默认值为 TASK_STEP_TIMEOUT

Feat task step timeout configurable

---

portal/web/middleware/auth.go

现在的 token header 为 Authorization: {{jwt_token}}，jwt 推荐格式为 Authorization: Bearer {{jwt_token}}
这个 pr 包含了这个兼容性支持。

Fix: 支持带 Bearer 的token

---

portal/apps/env.go

- 创建环境的时候步骤超时时间使用了错误的表单参数
- getTaskStepTimout 时间转换出错

fix: 修复 stepTimeout 错误问题

---

docs/lang.csv
portal/apps/env.go
portal/apps/template.go
portal/consts/e/errors.go
portal/services/template.go

当检测云模板的时候，选择历史部署选择的工作目录，tfvars文件、playbook文件已经revision当成一个云模板进行检测

fix:优化环境重新部署检测接口检测云模板规则

---

portal/models/env.go
runner/task.go

1. destroy时脚本字段缺失
2. env表的status字段增加 destroyed选项
```
ALTER TABLE cloudiac.iac_env MODIFY COLUMN status enum('active','failed','inactive','destroyed') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;
```

fix bug 脚本参数缺失和env表字段

---

runner/task.go

apply命令失败后，由于后续的采集信息命令执行成功，整个命令仍然返回成功。
修改后，apply命令的返回值作为最终的返回值

fix apply失败后整个命令仍然返回0

---

portal/apps/env.go

环境列表页面的 非活跃 tab 中包含 destroyed 数据

Fix 环境列表页面的 非活跃 tab 中包含 destroyed 数据

---

cmds/common/register.go
common/consts.go
configs/config.go
utils/consul/consul_client.go

服务重启时，由于上次关闭时，consul上的lock还没有释放（自动释放最快10s左右）。
10s内重启的话，无法启动成功。
目前的方案是启动时尝试2次获取锁，第一次获取失败后，等待 wait_lock_release （单位秒，默认20）。
此配置在 consul 下。

Fix service restart error

---

portal/services/task_step.go

ChangeTaskStepStatusAndExitCode() 修改 step.ExitCode 后未保存到 db，导致扫描步骤的 exitCode 总是为 0 ，
然后 ChangeScanTaskStatusWithStep() 函数中根据任务状态和 step.ExitCode 判断 policyStatus 时总是取了 PolicyStatusFailed

fix: 修复 opa 扫描不通过时未展示扫描结果的问题

---

portal/models/variables.go

创建索引时使用了 name(32)，但实际上 name 字段长度为 64，导致只要前 32 个字符相同就会包重复，实际变量名不同

fix: 变量名前 32 个字符重复会重名的问题

---

scripts/cloudiac-runner.sh

CloudIaC Runner 脚本
1. 将 cloudiac-runner.sh 和 terraform.py 放到 stack 目录下
2. 环境变量放在 .env 文件，terraform 变量放在 xx.tfvars 文件，编辑 cloudiac-runner.sh 修改 TF_VAR_FILE 指向 tfvars 文件。
3. 如果使用了 ansible 部署，需要配置 ssh 密钥，私钥编辑 cloudiac-runner.sh 修改 PRIVATE_KEY_FILE 指向私钥文件。
4. 执行：
```
部署: ./cloudiac-runner.sh
销毁: ./cloudiac-runner.sh destroy
```

CloudIaC Runner 脚本

---

runner/consts.go
runner/task.go

因为使用 TF_VAR_xx 环境变量传入会因为优先级问题导致无法覆盖掉 tfvars 文件中定义的变量，不便于 Stack 的编写。
改为这个方案后，我们可以支持在 stack 中定义不同的 tfvars 文件来对应不同部署场景的默认参数，然后在部署具体环境时对部分参数做修改。
terraform 变量的优先级定义：https://www.terraform.io/language/values/variables#variable-definition-precedence
改为该方案后用户依然可以通过在环境变量中配置带 TF_VAR_xx 前缀的变量。
需要注意，如果 tfvars 文件中有未定义的变量名 terraform 会报一个警告。

refa: 改用 tfvars.json 文件传入 terraform 变量

---

portal/apps/env.go

部署新环境时，步骤超时时间 不传 或者 传0 时，步骤超时时间取系统设置超时时间，并且以分钟为单位返回。

Fix 步骤超时时间出错

---

portal/consts/consts.go
portal/services/vcsrv/gitlab.go

由于 gitlab 的限制原因，新建 stack 时获取分支和 tags 只能获取到 100个。
所以当有 1000 个分支和 1000 个 tags 时，会分别请求 gitlab 接口 10 次，进而导致获取时间增加。

Fix 新建 stack 获取分支和 tags 只能获取 100

---

portal/apps/env.go
portal/services/task.go

新建 Stack 选择了 playbook 文件和 ssh 密钥，部署环境时删除 ssh，环境实际执行还是会使用 ssh。
分两种情况：
部署新环境：
协调前端修改，如果 keyid 为空，修改前不传 keyid 参数，修改后前端 keyid 传空。
重新部署：
1. 不传 keyid 参数时，默认取 env 的 keyid。
2.  当 keyid 传空时，在重新部署时，env keyid 和 form keyid 保持一致，都为空。在设置里删除 ssh 密钥后，stack 中的 ssh 密钥还存在，所以去 tpl 的 keyid 会出错。

Fix 重新部署时无法真正删除 ssh 密钥

---

portal/services/notificationrc/notificationservice.go

在部署环境时，分支可能选择的不是 stack 模版分支，但是事件通知时分支显示 stack 模版分支名称，正常应该显示目前环境部署使用的分支名称。

Fix 事件通知时分支显示 stack 分支名称

---

CHANGELOG.md
cmds/tool/db.go
portal/models/resource.go
portal/services/task.go

fix:修复资源列表无法识别datasource、resource
（表iac_resource新增mode字段，识别资源类型。datasource资源的mode字段为data，resource资源的mode资源为managed）。
数据升级：
通过执行 `./iac-tool updateDB resource -m` 进行数据升级。
如果是容器化部署执行: `docker-compose exec iac-portal ./iac-tool updateDB resource -m`

fix:新增mode字段识别datasource、resoucre

---

portal/services/env.go

查询中包含一个非聚合的列 iac_resource.attrs，而这个列不依赖于 group by 子句中的列。这在当前的sql_mode设置中与"only_full_group_by"不兼容。

fix: 环境费用统计接口报错 500
